### ISSUE TITLE
Move on python 3

### ISSUE THREAD

**Issue by dovudo** [dovudo/DwScript#21]
- Move the code on python3
- Check running 
- Check working
- Debug

**Comment by vatsalya-gupta** [comment]
I am quite proficient in python 3 and want to help.

**Comment by dovudo** [comment]
> I am quite proficient in python 3 and want to help.

Pretty nice, let's do this!

**Comment by vatsalya-gupta** [comment]
Updated the required files and raised pull request https://github.com/dovudo/DwScript/pull/24 @dovudo
